import json
import os
from pathlib import Path

# Paths
ROOT_DIR = Path(__file__).parent.parent.parent.parent
NCP_PATH = ROOT_DIR / 'aegis/ncp/kohaerenz_protokoll_v2.ncp.json'
NARRATIVE_DESIGN_DIR = ROOT_DIR / 'kohaerenz_protokoll/narrative_design'
ACTS_DIR = NARRATIVE_DESIGN_DIR / 'Acts'
STORY_DIR = ROOT_DIR / 'Story'

def load_ncp():
    with open(NCP_PATH, 'r', encoding='utf-8') as f:
        return json.load(f)

def ensure_dirs():
    os.makedirs(ACTS_DIR, exist_ok=True)

def generate_act_docs(ncp_data):
    acts = ncp_data.get('plot', {}).get('acts', [])

    act_files = []

    for act in acts:
        act_num = act.get('act')
        title = act.get('title')
        chapters_range = act.get('chapters')
        archetype = act.get('archetype')
        k_state = act.get('K_state')
        dramatic_arc = act.get('dramatic_arc')
        style_dominant = act.get('style_dominant')
        concepts = act.get('chapter_concepts', [])

        filename = f"Act_{act_num}_Design.md"
        filepath = ACTS_DIR / filename
        act_files.append((act_num, title, filename))

        content = f"# Act {act_num}: {title}\n\n"
        content += f"**Chapters**: {chapters_range}\n"
        content += f"**Archetype**: {archetype}\n"
        content += f"**K-State**: {k_state}\n"
        content += f"**Dramatic Arc**: {dramatic_arc}\n"
        content += f"**Style Dominant**: {style_dominant}\n\n"

        content += "## Chapter Concepts & Events\n\n"
        content += "| Chapter | Concept | Key Event | Manuscript |\n"
        content += "|---|---|---|---|\n"

        for c in concepts:
            ch_num = c.get('ch')
            concept = c.get('concept')
            event = c.get('event')

            # Link to Story/Chapter_XX.md
            # Assuming format Chapter_01.md, Chapter_10.md
            ch_str = f"{ch_num:02d}"
            story_link = f"../../Story/Chapter_{ch_str}.md"

            # Check if file exists to add a checkmark or similar?
            # For now, just a link.
            content += f"| {ch_num} | {concept} | {event} | [Chapter {ch_num}]({story_link}) |\n"

        content += "\n## Stasis-Lücken (if any)\n\n"
        stasis = act.get('stasis_luecken', [])
        if stasis:
            for s in stasis:
                content += f"- **Chapter {s.get('chapter')}**: {s.get('type')} - {s.get('content')}\n"
        else:
            content += "None listed in NCP.\n"

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)

        print(f"Generated {filepath}")

    return act_files

def generate_readme(ncp_data, act_files):
    filepath = NARRATIVE_DESIGN_DIR / 'README.md'

    title = ncp_data.get('meta', {}).get('title', 'Narrative Design')
    subtitle = ncp_data.get('meta', {}).get('subtitle', '')
    status = ncp_data.get('status', 'Unknown')

    content = f"# {title} - Narrative Design & Navigation\n\n"
    content += f"**Subtitle**: {subtitle}\n"
    content += f"**Status**: {status}\n\n"

    content += "## 🧭 Navigation\n\n"
    content += "This directory contains the narrative design documents and navigation guides for the Kohärenz Protokoll manuscript.\n\n"

    content += "### 📜 Acts & Chapters\n\n"
    for num, title, filename in act_files:
        content += f"- [Act {num}: {title}](Acts/{filename})\n"

    content += "\n### 📚 Core Documents\n\n"
    content += "- [**Project Codex**](../PROJECT_CODEX.md) (Generated from NCP)\n"
    content += "- [**NCP JSON Source**](../../aegis/ncp/kohaerenz_protokoll_v2.ncp.json) (Single Source of Truth)\n"
    content += "- [**Manuscript Folder**](../../Story/) (Raw Markdown Files)\n"

    content += "\n### 🛠 Narrative Analysis & Audits\n\n"
    # List other md files in the directory
    content += "| Document | Description |\n"
    content += "|---|---|\n"

    for file in sorted(os.listdir(NARRATIVE_DESIGN_DIR)):
        if file.endswith('.md') and file != 'README.md':
            # Skip if it's a directory (unlikely with listdir unless filtered)
            if (NARRATIVE_DESIGN_DIR / file).is_dir():
                continue

            # Simple description based on filename
            desc = file.replace('_', ' ').replace('.md', '').title()
            content += f"| [{file}]({file}) | {desc} |\n"

    content += "\n---\n"
    content += "*Generated by `skills/narrative_design/scripts/generate_narrative_design_docs.py`*\n"

    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(content)

    print(f"Generated {filepath}")

def main():
    print("Loading NCP...")
    ncp_data = load_ncp()

    print("Ensuring directories...")
    ensure_dirs()

    print("Generating Act docs...")
    act_files = generate_act_docs(ncp_data)

    print("Generating README...")
    generate_readme(ncp_data, act_files)

    print("Done.")

if __name__ == "__main__":
    main()
